# Generated by Django 4.1.4 on 2023-01-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(choices=[('1', 'Hindi'), ('2', 'English')], max_length=2),
        ),
    ]
