# Generated by Django 4.1.4 on 2023-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], max_length=20),
        ),
    ]
